### ISSUE TITLE
Add support for "enum" type

### ISSUE THREAD

**Issue by feserafim** [isa-group/governify-csp-tools#14]
This way, a user can model a CSP parameter with type "enum", i.e.

```yaml
parameters:
- id: enumParam
  values:
  - value1
  - value2
  # ...
```
